name = "DielectricUpdateTechique"
uuid = "af0db3c1-8357-4a5e-bd7b-9f2a566eac1f"
authors = ["Peter Stijnman <P.R.S.Stijnman@umcutrecht.nl> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
